### ISSUE TITLE
Debug Menu

### ISSUE THREAD

**Issue by havderick** [monoai/GDAPDEV_MP#13]
## Tasks
- [ ] Add decrease value buttons
- [x] Generate Notifications
- [x] Ads Testing
- [ ] Notification Interval Time (See more at #17 regarding this)
- [x] Level Selection (Should unlock all levels since our game can select levels in the first place)
- [ ] More cheats to ease debugging
