### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by monoai** [monoai/GDAPDEV_MP#18]
I'm also not sure if all types of Ads are needed but based on the lesson presentation itself, it might actually be **required** to insert the 3 types of Ads in the game.

Here are the ideas for the placement of the 3 types of Ads.
### Interstitial Ads
We can add these kinds of ads after the player finishes and goes back to the level selection screen, the game already features a level won feature so we could probably make them watch an ad right there, even if it sounds really annoying.
### Banner Ads
We could add these on the level selection screen only so that it would only appear there and wouldn't be much of a nuisance to the player.
### Rewarded Ads
There's only two ways we could implement these kinds of ads, we could add a "Get free *X* amount of currency" at the store, or when the player dies, give them the chance to revive at the cost of watching an ad. We could do both, but let's see from the time constraints if we could actually do it.

## Tasks

- [ ] Add Interstitial Ads
- [ ] Add Banner Ads
- [ ] Add Reward Ads
- [x] Enable/Disable Ads Toggle

**Comment by havderick** [comment]
Placed an Ads Toggle inside OptionsMenu
