### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by monoai** [monoai/GDAPDEV_MP#5]
Animations for the player, projectiles, enemies, etc.

## Tasks

- [x] #12 
- [ ] Enemy taking damage animation
- [ ] Enemy spawning animation
- [ ] Enemy dying
- [ ] Player taking damage animation
- [ ] Dodge mechanic animation

**Comment by monoai** [comment]
If possible, hopefully the animations would modify the sprites rather than needing new sprites.

**Comment by monoai** [comment]
Suggestion: For the laser, since it hits by fireRate instead of constantly by its beam, we could make it so that while it's dormant, it'll make anyone's sprite as blue until their damaged animation is triggered. Either this approach or just implement it specifically to the player to let them know they're still safe.
